name: GitVerse Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'

      # Собираем статику через наш action на основе jekyll
      - name: Build page with Jekyll
        uses: actions/jekyll-build-pages@master
        with:
          jekyll_env: production

      # Прикрепляем артефакт сборки
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Go необходим для выполнения deploy-pages
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'

      # Выполняем деплой GitVerse Pages через наш action
      - name: Deploy to GitVerse Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: gitverse-pages

      - name: Print deploy URL
        run: echo "🌐 page_url = ${{ steps.deployment.outputs.page_url }}"